language: java
jdk:
  - openjdk8
os:
  - linux
cache:
  directories:
    - ~/.m2/repository
install:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true --quiet --batch-mode --show-version --activate-profiles travis
script:
  - ./mvnw test jacoco:report coveralls:report --batch-mode --activate-profiles travis -DrepoToken=${COVERALLS_REPO_TOKEN}

